---
title: "p8105_hw2_cev2129"
output: github_document
date: "2024-10-02"
---

## Problem 1
```{r}
library(tidyverse)
library(dplyr)
library(readxl)
getwd()

nyc_transit = read_csv(file ="/Users/tinavarela/Desktop/github_document/p8105_hw2_cev2129/NYC_Transit_Subway_Entrance_And_Exit_Data.csv")

nyc_transit = janitor::clean_names(nyc_transit)

nyc_transit = select(nyc_transit, line, station_name, station_latitude, station_longitude, starts_with("route"), entry, vending, ada)

nyc_transit = nyc_transit %>% mutate(case_match(entry,
                             "YES" ~ TRUE,
                             "NO" ~  FALSE,                         
                               ))
```

This data set contains information of each subway station's demographics such as line, name, latitude, route, entry, vending, and ada. To clean the data I used the janitor::clean::names function, and then I selected for the speicifc columns I wanted to keep using the select() function. the dimensions of the table are 1,868 rows x 19 columns. These data are tidy.

```{r}

```

##Problem 2
```{r}
trash = read_excel("/Users/tinavarela/Desktop/github_document/p8105_hw2_cev2129/Trash_Wheel_Collection_Data.xlsx",sheet = "Mr. Trash Wheel", na = c("NA", ".", "")) |> 
  janitor::clean_names()|>
  select(-month, -year, -date, -homes_powered, -x15, -x16)|>
  drop_na()|>
  mutate(sports_balls = as.integer(round(sports_balls), 0))
```
```{r}
trash2 = read_excel("/Users/tinavarela/Desktop/github_document/p8105_hw2_cev2129/Trash_Wheel_Collection_Data.xlsx",sheet = "Professor Trash Wheel", na = c("NA", ".", "")) |> 
  janitor::clean_names()|>
  mutate(trashwheel = "Professor") |>
  select(-month, -year, -date, -homes_powered)|>
  drop_na()

trash3 = read_excel("/Users/tinavarela/Desktop/github_document/p8105_hw2_cev2129/Trash_Wheel_Collection_Data.xlsx",sheet = "Gwynnda Trash Wheel", na = c("NA", ".", "")) |> 
  janitor::clean_names()|>
  mutate(trashwheel = "Gwynnda")|>
  select(-month, -year, -date, -homes_powered)|>
  drop_na() 

trash = mutate(trash, trashwheel = "Mr")
```
```{r}

```

